[project]
name = "grades"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.25.1",
    "pandas>=2.3.3",
    "textual>=7.3.0",
]
